# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: west-commands.yml

  remotes:
    - name: jonathan-thomson
      url-base: https://github.com/jonathan-thomson
    - name: catchorg
      url-base: https://github.com/catchorg
    - name: meekrosoft
      url-base: https://github.com/meekrosoft

  projects:
    - name: zephyr
      remote: jonathan-thomson
      repo-path: zephyr.git
      revision: e72fd66378ccdef18ca864c7bc23a88604f695ed
      import:
        path-prefix: thirdparty/zephyrproject
        name-allowlist:
          - cmsis_6
          - hal_nxp
          - picolibc
          - segger
          - mbedtls
          
    - name: Catch2
      remote: catchorg
      revision: 644821ce28cb25d7992a4d0375b1d83214392592 # v3.9.1
      path: thirdparty/catch2

    - name: fff
      remote: meekrosoft
      revision: 7e09f07e5b262b1cc826189dc5057379e40ce886 # v1.1
      path: thirdparty/fff
